services:
  - type: web
    name: cvbuilder-web
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt && cd cvbuilder && python manage.py collectstatic --noinput
    startCommand: cd cvbuilder && gunicorn cvbuilder.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cvbuilder-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "cvbuilder-web.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://cvbuilder-web.onrender.com"
databases:
  - name: cvbuilder-db
    plan: free

